// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxpqpyohqfeysruzfuoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cHFweW9ocWZleXNydXpmdW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQ1NTQsImV4cCI6MjA2Mzc3MDU1NH0.6q76Y-e3PiFVT9z_CUr2Fzeoioz34ytvZuUT0hk9suE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);